export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
    "buckets": {
      Row: {
    "updated_at"?: string | null;
    "created_at"?: string | null;
    "owner_id"?: string | null;
    "allowed_mime_types"?: Array<string> | null;
    "file_size_limit"?: number | null;
    "avif_autodetection"?: boolean | null;
    "public"?: boolean | null;
    "name": string;
    "id": string;
      };
      Insert: {
    "updated_at"?: string | null;
    "created_at"?: string | null;
    "owner_id"?: string | null;
    "allowed_mime_types"?: Array<string> | null;
    "file_size_limit"?: number | null;
    "avif_autodetection"?: boolean | null;
    "public"?: boolean | null;
    "name": string;
    "id": string;
      };
      Update: {
    "updated_at"?: string | null;
    "created_at"?: string | null;
    "owner_id"?: string | null;
    "allowed_mime_types"?: Array<string> | null;
    "file_size_limit"?: number | null;
    "avif_autodetection"?: boolean | null;
    "public"?: boolean | null;
    "name"?: string;
    "id"?: string;
      };
      Relationships: [];
    };
    "objects": {
      Row: {
    "updated_at"?: string | null;
    "created_at"?: string | null;
    "last_accessed_at"?: string | null;
    "path_tokens"?: Array<string> | null;
    "user_metadata"?: Json | null;
    "metadata"?: Json | null;
    "owner_id"?: string | null;
    "bucket_id"?: string | null;
    "version"?: string | null;
    "name"?: string | null;
    "id"?: string;
      };
      Insert: {
    "updated_at"?: string | null;
    "created_at"?: string | null;
    "last_accessed_at"?: string | null;
    "user_metadata"?: Json | null;
    "metadata"?: Json | null;
    "owner_id"?: string | null;
    "bucket_id"?: string | null;
    "version"?: string | null;
    "name"?: string | null;
    "id"?: string;
      };
      Update: {
    "updated_at"?: string | null;
    "created_at"?: string | null;
    "last_accessed_at"?: string | null;
    "path_tokens"?: Array<string> | null;
    "user_metadata"?: Json | null;
    "metadata"?: Json | null;
    "owner_id"?: string | null;
    "bucket_id"?: string | null;
    "version"?: string | null;
    "name"?: string | null;
    "id"?: string;
      };
      Relationships: [];
    };
    "migrations": {
      Row: {
    "executed_at"?: string | null;
    "hash": string;
    "name": string;
    "id": number;
      };
      Insert: {
    "executed_at"?: string | null;
    "hash": string;
    "name": string;
    "id": number;
      };
      Update: {
    "executed_at"?: string | null;
    "hash"?: string;
    "name"?: string;
    "id"?: number;
      };
      Relationships: [];
    };
    "s3_multipart_uploads": {
      Row: {
    "created_at"?: string;
    "user_metadata"?: Json | null;
    "owner_id"?: string | null;
    "in_progress_size"?: number;
    "upload_signature": string;
    "version": string;
    "key": string;
    "bucket_id": string;
    "id": string;
      };
      Insert: {
    "created_at"?: string;
    "user_metadata"?: Json | null;
    "owner_id"?: string | null;
    "in_progress_size"?: number;
    "upload_signature": string;
    "version": string;
    "key": string;
    "bucket_id": string;
    "id": string;
      };
      Update: {
    "created_at"?: string;
    "user_metadata"?: Json | null;
    "owner_id"?: string | null;
    "in_progress_size"?: number;
    "upload_signature"?: string;
    "version"?: string;
    "key"?: string;
    "bucket_id"?: string;
    "id"?: string;
      };
      Relationships: [];
    };
    "schema_migrations": {
      Row: {
    "name"?: string | null;
    "statements"?: Array<string> | null;
    "version": string;
      };
      Insert: {
    "name"?: string | null;
    "statements"?: Array<string> | null;
    "version": string;
      };
      Update: {
    "name"?: string | null;
    "statements"?: Array<string> | null;
    "version"?: string;
      };
      Relationships: [];
    };
    "seed_files": {
      Row: {
    "hash": string;
    "path": string;
      };
      Insert: {
    "hash": string;
    "path": string;
      };
      Update: {
    "hash"?: string;
    "path"?: string;
      };
      Relationships: [];
    };
    "forum_categories": {
      Row: {
    "updated_at"?: string;
    "created_at"?: string;
    "is_archived"?: boolean;
    "sort_order"?: number;
    "description"?: string;
    "name": string;
    "slug": string;
    "id"?: string;
      };
      Insert: {
    "updated_at"?: string;
    "created_at"?: string;
    "is_archived"?: boolean;
    "sort_order"?: number;
    "description"?: string;
    "name": string;
    "slug": string;
    "id"?: string;
      };
      Update: {
    "updated_at"?: string;
    "created_at"?: string;
    "is_archived"?: boolean;
    "sort_order"?: number;
    "description"?: string;
    "name"?: string;
    "slug"?: string;
    "id"?: string;
      };
      Relationships: [];
    };
    "forum_posts": {
      Row: {
    "updated_at"?: string;
    "created_at"?: string;
    "reply_count"?: number;
    "like_count"?: number;
    "view_count"?: number;
    "status"?: string;
    "cover_url"?: string | null;
    "content": string;
    "title": string;
    "author_id"?: string;
    "category_id": string;
    "id"?: string;
      };
      Insert: {
    "updated_at"?: string;
    "created_at"?: string;
    "reply_count"?: number;
    "like_count"?: number;
    "view_count"?: number;
    "status"?: string;
    "cover_url"?: string | null;
    "content": string;
    "title": string;
    "author_id"?: string;
    "category_id": string;
    "id"?: string;
      };
      Update: {
    "updated_at"?: string;
    "created_at"?: string;
    "reply_count"?: number;
    "like_count"?: number;
    "view_count"?: number;
    "status"?: string;
    "cover_url"?: string | null;
    "content"?: string;
    "title"?: string;
    "author_id"?: string;
    "category_id"?: string;
    "id"?: string;
      };
      Relationships: [];
    };
    "forum_replies": {
      Row: {
    "updated_at"?: string;
    "created_at"?: string;
    "like_count"?: number;
    "status"?: string;
    "content": string;
    "parent_id"?: string | null;
    "author_id"?: string;
    "post_id": string;
    "id"?: string;
      };
      Insert: {
    "updated_at"?: string;
    "created_at"?: string;
    "like_count"?: number;
    "status"?: string;
    "content": string;
    "parent_id"?: string | null;
    "author_id"?: string;
    "post_id": string;
    "id"?: string;
      };
      Update: {
    "updated_at"?: string;
    "created_at"?: string;
    "like_count"?: number;
    "status"?: string;
    "content"?: string;
    "parent_id"?: string | null;
    "author_id"?: string;
    "post_id"?: string;
    "id"?: string;
      };
      Relationships: [];
    };
    "forum_post_likes": {
      Row: {
    "created_at"?: string;
    "user_id"?: string;
    "post_id": string;
      };
      Insert: {
    "created_at"?: string;
    "user_id"?: string;
    "post_id": string;
      };
      Update: {
    "created_at"?: string;
    "user_id"?: string;
    "post_id"?: string;
      };
      Relationships: [];
    };
    "forum_reply_likes": {
      Row: {
    "created_at"?: string;
    "user_id"?: string;
    "reply_id": string;
      };
      Insert: {
    "created_at"?: string;
    "user_id"?: string;
    "reply_id": string;
      };
      Update: {
    "created_at"?: string;
    "user_id"?: string;
    "reply_id"?: string;
      };
      Relationships: [];
    };
    "forum_attachments": {
      Row: {
    "created_at"?: string;
    "file_size": number;
    "mime_type": string;
    "object_key": string;
    "bucket_name": string;
    "reply_id"?: string | null;
    "post_id"?: string | null;
    "uploader_id"?: string;
    "id"?: string;
      };
      Insert: {
    "created_at"?: string;
    "file_size": number;
    "mime_type": string;
    "object_key": string;
    "bucket_name": string;
    "reply_id"?: string | null;
    "post_id"?: string | null;
    "uploader_id"?: string;
    "id"?: string;
      };
      Update: {
    "created_at"?: string;
    "file_size"?: number;
    "mime_type"?: string;
    "object_key"?: string;
    "bucket_name"?: string;
    "reply_id"?: string | null;
    "post_id"?: string | null;
    "uploader_id"?: string;
    "id"?: string;
      };
      Relationships: [];
    };
    "forum_reports": {
      Row: {
    "created_at"?: string;
    "handled_at"?: string | null;
    "handled_by"?: string | null;
    "status"?: string;
    "description"?: string;
    "reason": string;
    "target_id": string;
    "target_type": string;
    "reporter_id"?: string;
    "id"?: string;
      };
      Insert: {
    "created_at"?: string;
    "handled_at"?: string | null;
    "handled_by"?: string | null;
    "status"?: string;
    "description"?: string;
    "reason": string;
    "target_id": string;
    "target_type": string;
    "reporter_id"?: string;
    "id"?: string;
      };
      Update: {
    "created_at"?: string;
    "handled_at"?: string | null;
    "handled_by"?: string | null;
    "status"?: string;
    "description"?: string;
    "reason"?: string;
    "target_id"?: string;
    "target_type"?: string;
    "reporter_id"?: string;
    "id"?: string;
      };
      Relationships: [];
    };
    "s3_multipart_uploads_parts": {
      Row: {
    "created_at"?: string;
    "owner_id"?: string | null;
    "etag": string;
    "size"?: number;
    "version": string;
    "part_number": number;
    "key": string;
    "bucket_id": string;
    "upload_id": string;
    "id"?: string;
      };
      Insert: {
    "created_at"?: string;
    "owner_id"?: string | null;
    "etag": string;
    "size"?: number;
    "version": string;
    "part_number": number;
    "key": string;
    "bucket_id": string;
    "upload_id": string;
    "id"?: string;
      };
      Update: {
    "created_at"?: string;
    "owner_id"?: string | null;
    "etag"?: string;
    "size"?: number;
    "version"?: string;
    "part_number"?: number;
    "key"?: string;
    "bucket_id"?: string;
    "upload_id"?: string;
    "id"?: string;
      };
      Relationships: [];
    };
    "audit_log_entries": {
      Row: {
    "expires_at"?: string | null;
    "user_id"?: string | null;
    "meta"?: Json | null;
    "action"?: number | null;
    "created_at"?: string | null;
    "device_id"?: string | null;
    "client_id"?: string | null;
    "user_agent"?: string | null;
    "ip"?: string | null;
    "uuid"?: string | null;
    "project": string;
    "id"?: number;
      };
      Insert: {
    "expires_at"?: string | null;
    "user_id"?: string | null;
    "meta"?: Json | null;
    "action"?: number | null;
    "created_at"?: string | null;
    "device_id"?: string | null;
    "client_id"?: string | null;
    "user_agent"?: string | null;
    "ip"?: string | null;
    "uuid"?: string | null;
    "project": string;
    "id"?: number;
      };
      Update: {
    "expires_at"?: string | null;
    "user_id"?: string | null;
    "meta"?: Json | null;
    "action"?: number | null;
    "created_at"?: string | null;
    "device_id"?: string | null;
    "client_id"?: string | null;
    "user_agent"?: string | null;
    "ip"?: string | null;
    "uuid"?: string | null;
    "project"?: string;
    "id"?: number;
      };
      Relationships: [];
    };
    "token": {
      Row: {
    "provider_type"?: string | null;
    "user_type"?: string | null;
    "token_type"?: string | null;
    "meta"?: Json | null;
    "once"?: string | null;
    "groups"?: Json | null;
    "user_agent"?: string | null;
    "device_id"?: string | null;
    "client_type"?: number | null;
    "client_id"?: string | null;
    "user_id"?: string | null;
    "access_expires_at"?: string | null;
    "expires_at"?: string | null;
    "expires_in"?: number | null;
    "created_at"?: string | null;
    "updated_at"?: string | null;
    "scopes"?: Json | null;
    "refresh_token"?: string | null;
    "at_hash"?: string | null;
    "project": string;
    "id": string;
      };
      Insert: {
    "provider_type"?: string | null;
    "user_type"?: string | null;
    "token_type"?: string | null;
    "meta"?: Json | null;
    "once"?: string | null;
    "groups"?: Json | null;
    "user_agent"?: string | null;
    "device_id"?: string | null;
    "client_type"?: number | null;
    "client_id"?: string | null;
    "user_id"?: string | null;
    "access_expires_at"?: string | null;
    "expires_at"?: string | null;
    "expires_in"?: number | null;
    "created_at"?: string | null;
    "updated_at"?: string | null;
    "scopes"?: Json | null;
    "refresh_token"?: string | null;
    "at_hash"?: string | null;
    "project": string;
    "id": string;
      };
      Update: {
    "provider_type"?: string | null;
    "user_type"?: string | null;
    "token_type"?: string | null;
    "meta"?: Json | null;
    "once"?: string | null;
    "groups"?: Json | null;
    "user_agent"?: string | null;
    "device_id"?: string | null;
    "client_type"?: number | null;
    "client_id"?: string | null;
    "user_id"?: string | null;
    "access_expires_at"?: string | null;
    "expires_at"?: string | null;
    "expires_in"?: number | null;
    "created_at"?: string | null;
    "updated_at"?: string | null;
    "scopes"?: Json | null;
    "refresh_token"?: string | null;
    "at_hash"?: string | null;
    "project"?: string;
    "id"?: string;
      };
      Relationships: [];
    };
    "provider_token": {
      Row: {
    "provider_type"?: string | null;
    "user_type"?: string | null;
    "id_token"?: string | null;
    "token_type"?: string | null;
    "meta"?: Json | null;
    "once"?: string | null;
    "groups"?: Json | null;
    "user_agent"?: string | null;
    "device_id"?: string | null;
    "organization_id"?: string | null;
    "organization_user_id"?: string | null;
    "client_type"?: number | null;
    "client_id"?: string | null;
    "user_id"?: string | null;
    "access_expires_at"?: string | null;
    "expires_at"?: string | null;
    "expires_in"?: number | null;
    "created_at"?: string | null;
    "updated_at"?: string | null;
    "scopes"?: Json | null;
    "refresh_token"?: string | null;
    "at_hash"?: string | null;
    "is_id_token"?: boolean | null;
    "access_token"?: string | null;
    "project": string;
    "id": string;
      };
      Insert: {
    "provider_type"?: string | null;
    "user_type"?: string | null;
    "id_token"?: string | null;
    "token_type"?: string | null;
    "meta"?: Json | null;
    "once"?: string | null;
    "groups"?: Json | null;
    "user_agent"?: string | null;
    "device_id"?: string | null;
    "organization_id"?: string | null;
    "organization_user_id"?: string | null;
    "client_type"?: number | null;
    "client_id"?: string | null;
    "user_id"?: string | null;
    "access_expires_at"?: string | null;
    "expires_at"?: string | null;
    "expires_in"?: number | null;
    "created_at"?: string | null;
    "updated_at"?: string | null;
    "scopes"?: Json | null;
    "refresh_token"?: string | null;
    "at_hash"?: string | null;
    "is_id_token"?: boolean | null;
    "access_token"?: string | null;
    "project": string;
    "id": string;
      };
      Update: {
    "provider_type"?: string | null;
    "user_type"?: string | null;
    "id_token"?: string | null;
    "token_type"?: string | null;
    "meta"?: Json | null;
    "once"?: string | null;
    "groups"?: Json | null;
    "user_agent"?: string | null;
    "device_id"?: string | null;
    "organization_id"?: string | null;
    "organization_user_id"?: string | null;
    "client_type"?: number | null;
    "client_id"?: string | null;
    "user_id"?: string | null;
    "access_expires_at"?: string | null;
    "expires_at"?: string | null;
    "expires_in"?: number | null;
    "created_at"?: string | null;
    "updated_at"?: string | null;
    "scopes"?: Json | null;
    "refresh_token"?: string | null;
    "at_hash"?: string | null;
    "is_id_token"?: boolean | null;
    "access_token"?: string | null;
    "project"?: string;
    "id"?: string;
      };
      Relationships: [];
    };
    "apikey_token": {
      Row: {
    "user_agent"?: string | null;
    "device_id"?: string | null;
    "key_type"?: string | null;
    "expires_at"?: string | null;
    "expires_in"?: number | null;
    "created_at"?: string | null;
    "updated_at"?: string | null;
    "at_hash"?: string | null;
    "name"?: string | null;
    "project": string;
    "id": string;
      };
      Insert: {
    "user_agent"?: string | null;
    "device_id"?: string | null;
    "key_type"?: string | null;
    "expires_at"?: string | null;
    "expires_in"?: number | null;
    "created_at"?: string | null;
    "updated_at"?: string | null;
    "at_hash"?: string | null;
    "name"?: string | null;
    "project": string;
    "id": string;
      };
      Update: {
    "user_agent"?: string | null;
    "device_id"?: string | null;
    "key_type"?: string | null;
    "expires_at"?: string | null;
    "expires_in"?: number | null;
    "created_at"?: string | null;
    "updated_at"?: string | null;
    "at_hash"?: string | null;
    "name"?: string | null;
    "project"?: string;
    "id"?: string;
      };
      Relationships: [];
    };
    "users": {
      Row: {
    "main_dep"?: string | null;
    "parent_user_id"?: string | null;
    "corp_id"?: string | null;
    "open_id"?: string | null;
    "user_desc"?: string | null;
    "user_source"?: number | null;
    "type"?: string | null;
    "internal_user_type"?: string | null;
    "register_info"?: Json | null;
    "two_factor"?: Json | null;
    "last_login"?: string | null;
    "password_updated_at"?: string | null;
    "updated_at"?: string | null;
    "created_at"?: string | null;
    "created_from"?: string | null;
    "raw_app_meta_data"?: Json | null;
    "address"?: Json | null;
    "position"?: string | null;
    "groups"?: Json | null;
    "locale"?: string | null;
    "zoneinfo"?: string | null;
    "birthdate"?: string | null;
    "gender"?: string | null;
    "status"?: number | null;
    "password"?: string | null;
    "providers"?: Json | null;
    "phone_number"?: string | null;
    "email_verified"?: boolean | null;
    "email"?: string | null;
    "username"?: string | null;
    "picture"?: string | null;
    "name"?: string | null;
    "sub"?: string | null;
    "project": string;
    "id"?: number;
      };
      Insert: {
    "main_dep"?: string | null;
    "parent_user_id"?: string | null;
    "corp_id"?: string | null;
    "open_id"?: string | null;
    "user_desc"?: string | null;
    "user_source"?: number | null;
    "type"?: string | null;
    "internal_user_type"?: string | null;
    "register_info"?: Json | null;
    "two_factor"?: Json | null;
    "last_login"?: string | null;
    "password_updated_at"?: string | null;
    "updated_at"?: string | null;
    "created_at"?: string | null;
    "created_from"?: string | null;
    "raw_app_meta_data"?: Json | null;
    "address"?: Json | null;
    "position"?: string | null;
    "groups"?: Json | null;
    "locale"?: string | null;
    "zoneinfo"?: string | null;
    "birthdate"?: string | null;
    "gender"?: string | null;
    "status"?: number | null;
    "password"?: string | null;
    "providers"?: Json | null;
    "phone_number"?: string | null;
    "email_verified"?: boolean | null;
    "email"?: string | null;
    "username"?: string | null;
    "picture"?: string | null;
    "name"?: string | null;
    "sub"?: string | null;
    "project": string;
    "id"?: number;
      };
      Update: {
    "main_dep"?: string | null;
    "parent_user_id"?: string | null;
    "corp_id"?: string | null;
    "open_id"?: string | null;
    "user_desc"?: string | null;
    "user_source"?: number | null;
    "type"?: string | null;
    "internal_user_type"?: string | null;
    "register_info"?: Json | null;
    "two_factor"?: Json | null;
    "last_login"?: string | null;
    "password_updated_at"?: string | null;
    "updated_at"?: string | null;
    "created_at"?: string | null;
    "created_from"?: string | null;
    "raw_app_meta_data"?: Json | null;
    "address"?: Json | null;
    "position"?: string | null;
    "groups"?: Json | null;
    "locale"?: string | null;
    "zoneinfo"?: string | null;
    "birthdate"?: string | null;
    "gender"?: string | null;
    "status"?: number | null;
    "password"?: string | null;
    "providers"?: Json | null;
    "phone_number"?: string | null;
    "email_verified"?: boolean | null;
    "email"?: string | null;
    "username"?: string | null;
    "picture"?: string | null;
    "name"?: string | null;
    "sub"?: string | null;
    "project"?: string;
    "id"?: number;
      };
      Relationships: [];
    };
    "users_history": {
      Row: {
    "main_dep"?: string | null;
    "parent_user_id"?: string | null;
    "corp_id"?: string | null;
    "open_id"?: string | null;
    "user_desc"?: string | null;
    "user_source"?: number | null;
    "type"?: string | null;
    "internal_user_type"?: string | null;
    "register_info"?: Json | null;
    "two_factor"?: Json | null;
    "last_login"?: string | null;
    "password_updated_at"?: string | null;
    "updated_at"?: string | null;
    "created_at"?: string | null;
    "created_from"?: string | null;
    "raw_app_meta_data"?: Json | null;
    "address"?: Json | null;
    "position"?: string | null;
    "groups"?: Json | null;
    "locale"?: string | null;
    "zoneinfo"?: string | null;
    "birthdate"?: string | null;
    "gender"?: string | null;
    "status"?: number | null;
    "password"?: string | null;
    "providers"?: Json | null;
    "phone_number"?: string | null;
    "email_verified"?: boolean | null;
    "email"?: string | null;
    "username"?: string | null;
    "picture"?: string | null;
    "name"?: string | null;
    "sub"?: string | null;
    "project": string;
    "id"?: number;
      };
      Insert: {
    "main_dep"?: string | null;
    "parent_user_id"?: string | null;
    "corp_id"?: string | null;
    "open_id"?: string | null;
    "user_desc"?: string | null;
    "user_source"?: number | null;
    "type"?: string | null;
    "internal_user_type"?: string | null;
    "register_info"?: Json | null;
    "two_factor"?: Json | null;
    "last_login"?: string | null;
    "password_updated_at"?: string | null;
    "updated_at"?: string | null;
    "created_at"?: string | null;
    "created_from"?: string | null;
    "raw_app_meta_data"?: Json | null;
    "address"?: Json | null;
    "position"?: string | null;
    "groups"?: Json | null;
    "locale"?: string | null;
    "zoneinfo"?: string | null;
    "birthdate"?: string | null;
    "gender"?: string | null;
    "status"?: number | null;
    "password"?: string | null;
    "providers"?: Json | null;
    "phone_number"?: string | null;
    "email_verified"?: boolean | null;
    "email"?: string | null;
    "username"?: string | null;
    "picture"?: string | null;
    "name"?: string | null;
    "sub"?: string | null;
    "project": string;
    "id"?: number;
      };
      Update: {
    "main_dep"?: string | null;
    "parent_user_id"?: string | null;
    "corp_id"?: string | null;
    "open_id"?: string | null;
    "user_desc"?: string | null;
    "user_source"?: number | null;
    "type"?: string | null;
    "internal_user_type"?: string | null;
    "register_info"?: Json | null;
    "two_factor"?: Json | null;
    "last_login"?: string | null;
    "password_updated_at"?: string | null;
    "updated_at"?: string | null;
    "created_at"?: string | null;
    "created_from"?: string | null;
    "raw_app_meta_data"?: Json | null;
    "address"?: Json | null;
    "position"?: string | null;
    "groups"?: Json | null;
    "locale"?: string | null;
    "zoneinfo"?: string | null;
    "birthdate"?: string | null;
    "gender"?: string | null;
    "status"?: number | null;
    "password"?: string | null;
    "providers"?: Json | null;
    "phone_number"?: string | null;
    "email_verified"?: boolean | null;
    "email"?: string | null;
    "username"?: string | null;
    "picture"?: string | null;
    "name"?: string | null;
    "sub"?: string | null;
    "project"?: string;
    "id"?: number;
      };
      Relationships: [];
    };
    "client": {
      Row: {
    "providers"?: Json | null;
    "server_name"?: string | null;
    "redirect_uri"?: Json | null;
    "secrets"?: Json | null;
    "platform"?: number | null;
    "updated_at"?: string | null;
    "created_at"?: string | null;
    "meta"?: Json | null;
    "access_token_expires_in"?: number | null;
    "refresh_token_expires_in"?: number | null;
    "url"?: string | null;
    "status"?: number | null;
    "tags"?: Json | null;
    "ip_whitelist"?: Json | null;
    "domains"?: Json | null;
    "allowed_scopes"?: Json | null;
    "max_device"?: number | null;
    "level"?: number | null;
    "type"?: number | null;
    "show_authorize_page"?: number | null;
    "picture"?: string | null;
    "description"?: Json | null;
    "name"?: Json | null;
    "secret"?: string | null;
    "uuid"?: string | null;
    "project": string;
    "id"?: number;
      };
      Insert: {
    "providers"?: Json | null;
    "server_name"?: string | null;
    "redirect_uri"?: Json | null;
    "secrets"?: Json | null;
    "platform"?: number | null;
    "updated_at"?: string | null;
    "created_at"?: string | null;
    "meta"?: Json | null;
    "access_token_expires_in"?: number | null;
    "refresh_token_expires_in"?: number | null;
    "url"?: string | null;
    "status"?: number | null;
    "tags"?: Json | null;
    "ip_whitelist"?: Json | null;
    "domains"?: Json | null;
    "allowed_scopes"?: Json | null;
    "max_device"?: number | null;
    "level"?: number | null;
    "type"?: number | null;
    "show_authorize_page"?: number | null;
    "picture"?: string | null;
    "description"?: Json | null;
    "name"?: Json | null;
    "secret"?: string | null;
    "uuid"?: string | null;
    "project": string;
    "id"?: number;
      };
      Update: {
    "providers"?: Json | null;
    "server_name"?: string | null;
    "redirect_uri"?: Json | null;
    "secrets"?: Json | null;
    "platform"?: number | null;
    "updated_at"?: string | null;
    "created_at"?: string | null;
    "meta"?: Json | null;
    "access_token_expires_in"?: number | null;
    "refresh_token_expires_in"?: number | null;
    "url"?: string | null;
    "status"?: number | null;
    "tags"?: Json | null;
    "ip_whitelist"?: Json | null;
    "domains"?: Json | null;
    "allowed_scopes"?: Json | null;
    "max_device"?: number | null;
    "level"?: number | null;
    "type"?: number | null;
    "show_authorize_page"?: number | null;
    "picture"?: string | null;
    "description"?: Json | null;
    "name"?: Json | null;
    "secret"?: string | null;
    "uuid"?: string | null;
    "project"?: string;
    "id"?: number;
      };
      Relationships: [];
    };
    "config": {
      Row: {
    "pwd_update_strategy"?: Json | null;
    "mfa"?: Json | null;
    "status"?: Json | null;
    "client_limit"?: number | null;
    "user_admin_limit"?: number | null;
    "user_register_limit"?: number | null;
    "auth_disable"?: number | null;
    "audit"?: number | null;
    "ugc"?: number | null;
    "base_url"?: string | null;
    "rate_limit_edit_name"?: Json | null;
    "user_name_type"?: Json | null;
    "user_id_type"?: Json | null;
    "sender"?: Json | null;
    "access_endpoint"?: string | null;
    "oauth_device_authorization_endpoint"?: string | null;
    "oauth_authorization_endpoint"?: string | null;
    "enable_token_login"?: number | null;
    "enable_advanced_captcha"?: number | null;
    "email_match"?: string | null;
    "phone_number_match"?: string | null;
    "register_rate_limit"?: Json | null;
    "username_login"?: number | null;
    "anonymous_login"?: number | null;
    "email_login"?: number | null;
    "phone_number_login"?: number | null;
    "project": string;
    "id"?: number;
      };
      Insert: {
    "pwd_update_strategy"?: Json | null;
    "mfa"?: Json | null;
    "status"?: Json | null;
    "client_limit"?: number | null;
    "user_admin_limit"?: number | null;
    "user_register_limit"?: number | null;
    "auth_disable"?: number | null;
    "audit"?: number | null;
    "ugc"?: number | null;
    "base_url"?: string | null;
    "rate_limit_edit_name"?: Json | null;
    "user_name_type"?: Json | null;
    "user_id_type"?: Json | null;
    "sender"?: Json | null;
    "access_endpoint"?: string | null;
    "oauth_device_authorization_endpoint"?: string | null;
    "oauth_authorization_endpoint"?: string | null;
    "enable_token_login"?: number | null;
    "enable_advanced_captcha"?: number | null;
    "email_match"?: string | null;
    "phone_number_match"?: string | null;
    "register_rate_limit"?: Json | null;
    "username_login"?: number | null;
    "anonymous_login"?: number | null;
    "email_login"?: number | null;
    "phone_number_login"?: number | null;
    "project": string;
    "id"?: number;
      };
      Update: {
    "pwd_update_strategy"?: Json | null;
    "mfa"?: Json | null;
    "status"?: Json | null;
    "client_limit"?: number | null;
    "user_admin_limit"?: number | null;
    "user_register_limit"?: number | null;
    "auth_disable"?: number | null;
    "audit"?: number | null;
    "ugc"?: number | null;
    "base_url"?: string | null;
    "rate_limit_edit_name"?: Json | null;
    "user_name_type"?: Json | null;
    "user_id_type"?: Json | null;
    "sender"?: Json | null;
    "access_endpoint"?: string | null;
    "oauth_device_authorization_endpoint"?: string | null;
    "oauth_authorization_endpoint"?: string | null;
    "enable_token_login"?: number | null;
    "enable_advanced_captcha"?: number | null;
    "email_match"?: string | null;
    "phone_number_match"?: string | null;
    "register_rate_limit"?: Json | null;
    "username_login"?: number | null;
    "anonymous_login"?: number | null;
    "email_login"?: number | null;
    "phone_number_login"?: number | null;
    "project"?: string;
    "id"?: number;
      };
      Relationships: [];
    };
    "config_tpl": {
      Row: {
    "usages"?: Json | null;
    "sms_validate"?: Json | null;
    "email_validate"?: Json | null;
    "locale"?: string | null;
    "project": string;
    "id"?: number;
      };
      Insert: {
    "usages"?: Json | null;
    "sms_validate"?: Json | null;
    "email_validate"?: Json | null;
    "locale"?: string | null;
    "project": string;
    "id"?: number;
      };
      Update: {
    "usages"?: Json | null;
    "sms_validate"?: Json | null;
    "email_validate"?: Json | null;
    "locale"?: string | null;
    "project"?: string;
    "id"?: number;
      };
      Relationships: [];
    };
    "provider": {
      Row: {
    "email_config"?: Json | null;
    "bind_clients"?: Json | null;
    "forbidden_update_sub_type"?: number | null;
    "provider_sub_type"?: number | null;
    "mfa"?: number | null;
    "token_with_provider_sub"?: number | null;
    "type"?: string | null;
    "register_new_user"?: number | null;
    "must_bind_account"?: number | null;
    "reuse_user_id"?: number | null;
    "transparent_mode"?: number | null;
    "updated_at"?: string | null;
    "created_at"?: string | null;
    "hidden"?: number | null;
    "enabled"?: number | null;
    "auto_sign_in_when_phone_number_match"?: number | null;
    "auto_sign_in_when_email_match"?: number | null;
    "auto_sign_up_with_provider_user"?: number | null;
    "profile_do_not_must_have_user_id"?: number | null;
    "trusted_email_host"?: Json | null;
    "profile_phone_number_prefix"?: string | null;
    "provider_default_user_name"?: string | null;
    "provider_type"?: number | null;
    "provider_id"?: string | null;
    "config"?: Json | null;
    "picture"?: string | null;
    "homepage"?: string | null;
    "description"?: Json | null;
    "name"?: Json | null;
    "uuid"?: string | null;
    "project": string;
    "id"?: number;
      };
      Insert: {
    "email_config"?: Json | null;
    "bind_clients"?: Json | null;
    "forbidden_update_sub_type"?: number | null;
    "provider_sub_type"?: number | null;
    "mfa"?: number | null;
    "token_with_provider_sub"?: number | null;
    "type"?: string | null;
    "register_new_user"?: number | null;
    "must_bind_account"?: number | null;
    "reuse_user_id"?: number | null;
    "transparent_mode"?: number | null;
    "updated_at"?: string | null;
    "created_at"?: string | null;
    "hidden"?: number | null;
    "enabled"?: number | null;
    "auto_sign_in_when_phone_number_match"?: number | null;
    "auto_sign_in_when_email_match"?: number | null;
    "auto_sign_up_with_provider_user"?: number | null;
    "profile_do_not_must_have_user_id"?: number | null;
    "trusted_email_host"?: Json | null;
    "profile_phone_number_prefix"?: string | null;
    "provider_default_user_name"?: string | null;
    "provider_type"?: number | null;
    "provider_id"?: string | null;
    "config"?: Json | null;
    "picture"?: string | null;
    "homepage"?: string | null;
    "description"?: Json | null;
    "name"?: Json | null;
    "uuid"?: string | null;
    "project": string;
    "id"?: number;
      };
      Update: {
    "email_config"?: Json | null;
    "bind_clients"?: Json | null;
    "forbidden_update_sub_type"?: number | null;
    "provider_sub_type"?: number | null;
    "mfa"?: number | null;
    "token_with_provider_sub"?: number | null;
    "type"?: string | null;
    "register_new_user"?: number | null;
    "must_bind_account"?: number | null;
    "reuse_user_id"?: number | null;
    "transparent_mode"?: number | null;
    "updated_at"?: string | null;
    "created_at"?: string | null;
    "hidden"?: number | null;
    "enabled"?: number | null;
    "auto_sign_in_when_phone_number_match"?: number | null;
    "auto_sign_in_when_email_match"?: number | null;
    "auto_sign_up_with_provider_user"?: number | null;
    "profile_do_not_must_have_user_id"?: number | null;
    "trusted_email_host"?: Json | null;
    "profile_phone_number_prefix"?: string | null;
    "provider_default_user_name"?: string | null;
    "provider_type"?: number | null;
    "provider_id"?: string | null;
    "config"?: Json | null;
    "picture"?: string | null;
    "homepage"?: string | null;
    "description"?: Json | null;
    "name"?: Json | null;
    "uuid"?: string | null;
    "project"?: string;
    "id"?: number;
      };
      Relationships: [];
    };
    "identity": {
      Row: {
    "updated_at"?: string | null;
    "created_at"?: string | null;
    "expires_in"?: number | null;
    "refresh_token"?: string | null;
    "access_token"?: string | null;
    "username"?: string | null;
    "sub"?: string | null;
    "provider_user_id": string;
    "provider_type"?: string | null;
    "provider_id": string;
    "project": string;
    "id"?: number;
      };
      Insert: {
    "updated_at"?: string | null;
    "created_at"?: string | null;
    "expires_in"?: number | null;
    "refresh_token"?: string | null;
    "access_token"?: string | null;
    "username"?: string | null;
    "sub"?: string | null;
    "provider_user_id": string;
    "provider_type"?: string | null;
    "provider_id": string;
    "project": string;
    "id"?: number;
      };
      Update: {
    "updated_at"?: string | null;
    "created_at"?: string | null;
    "expires_in"?: number | null;
    "refresh_token"?: string | null;
    "access_token"?: string | null;
    "username"?: string | null;
    "sub"?: string | null;
    "provider_user_id"?: string;
    "provider_type"?: string | null;
    "provider_id"?: string;
    "project"?: string;
    "id"?: number;
      };
      Relationships: [];
    };
    "mfa_factors": {
      Row: {
    "created_at"?: string | null;
    "recovery"?: Json | null;
    "secret"?: string | null;
    "user_id"?: string | null;
    "project": string;
    "id"?: number;
      };
      Insert: {
    "created_at"?: string | null;
    "recovery"?: Json | null;
    "secret"?: string | null;
    "user_id"?: string | null;
    "project": string;
    "id"?: number;
      };
      Update: {
    "created_at"?: string | null;
    "recovery"?: Json | null;
    "secret"?: string | null;
    "user_id"?: string | null;
    "project"?: string;
    "id"?: number;
      };
      Relationships: [];
    };
    "counter": {
      Row: {
    "count"?: number | null;
    "key"?: string | null;
    "project": string;
    "id"?: number;
      };
      Insert: {
    "count"?: number | null;
    "key"?: string | null;
    "project": string;
    "id"?: number;
      };
      Update: {
    "count"?: number | null;
    "key"?: string | null;
    "project"?: string;
    "id"?: number;
      };
      Relationships: [];
    };
    "authorized": {
      Row: {
    "expires_at"?: string | null;
    "updated_at"?: string | null;
    "scopes"?: Json | null;
    "client_id"?: string | null;
    "user_id"?: string | null;
    "project": string;
    "id"?: number;
      };
      Insert: {
    "expires_at"?: string | null;
    "updated_at"?: string | null;
    "scopes"?: Json | null;
    "client_id"?: string | null;
    "user_id"?: string | null;
    "project": string;
    "id"?: number;
      };
      Update: {
    "expires_at"?: string | null;
    "updated_at"?: string | null;
    "scopes"?: Json | null;
    "client_id"?: string | null;
    "user_id"?: string | null;
    "project"?: string;
    "id"?: number;
      };
      Relationships: [];
    };
    "org": {
      Row: {
    "updated_by"?: string | null;
    "created_by"?: string | null;
    "created_at"?: string | null;
    "updated_at"?: string | null;
    "sort"?: number | null;
    "source"?: number | null;
    "depth"?: number | null;
    "parent_code"?: string | null;
    "name": string;
    "code": string;
    "dep_id": string;
    "project": string;
    "id"?: number;
      };
      Insert: {
    "updated_by"?: string | null;
    "created_by"?: string | null;
    "created_at"?: string | null;
    "updated_at"?: string | null;
    "sort"?: number | null;
    "source"?: number | null;
    "depth"?: number | null;
    "parent_code"?: string | null;
    "name": string;
    "code": string;
    "dep_id": string;
    "project": string;
    "id"?: number;
      };
      Update: {
    "updated_by"?: string | null;
    "created_by"?: string | null;
    "created_at"?: string | null;
    "updated_at"?: string | null;
    "sort"?: number | null;
    "source"?: number | null;
    "depth"?: number | null;
    "parent_code"?: string | null;
    "name"?: string;
    "code"?: string;
    "dep_id"?: string;
    "project"?: string;
    "id"?: number;
      };
      Relationships: [];
    };
    "user_org": {
      Row: {
    "updated_by"?: string | null;
    "created_by"?: string | null;
    "created_at"?: string | null;
    "updated_at"?: string | null;
    "org_type"?: number | null;
    "user_id": string;
    "org_id": string;
    "project": string;
    "id"?: number;
      };
      Insert: {
    "updated_by"?: string | null;
    "created_by"?: string | null;
    "created_at"?: string | null;
    "updated_at"?: string | null;
    "org_type"?: number | null;
    "user_id": string;
    "org_id": string;
    "project": string;
    "id"?: number;
      };
      Update: {
    "updated_by"?: string | null;
    "created_by"?: string | null;
    "created_at"?: string | null;
    "updated_at"?: string | null;
    "org_type"?: number | null;
    "user_id"?: string;
    "org_id"?: string;
    "project"?: string;
    "id"?: number;
      };
      Relationships: [];
    };
    "custom_key": {
      Row: {
    "created_at"?: string | null;
    "expires_at"?: string | null;
    "public_key"?: string | null;
    "key_id": string;
    "project": string;
    "id"?: number;
      };
      Insert: {
    "created_at"?: string | null;
    "expires_at"?: string | null;
    "public_key"?: string | null;
    "key_id": string;
    "project": string;
    "id"?: number;
      };
      Update: {
    "created_at"?: string | null;
    "expires_at"?: string | null;
    "public_key"?: string | null;
    "key_id"?: string;
    "project"?: string;
    "id"?: number;
      };
      Relationships: [];
    };
    "user_visit_events": {
      Row: {
    "date"?: string | null;
    "user_type"?: string | null;
    "user_id"?: string | null;
    "sub": string;
    "project": string;
    "id"?: number;
      };
      Insert: {
    "date"?: string | null;
    "user_type"?: string | null;
    "user_id"?: string | null;
    "sub": string;
    "project": string;
    "id"?: number;
      };
      Update: {
    "date"?: string | null;
    "user_type"?: string | null;
    "user_id"?: string | null;
    "sub"?: string;
    "project"?: string;
    "id"?: number;
      };
      Relationships: [];
    };
    "user_visit_mau": {
      Row: {
    "wx_anonymous_users"?: number | null;
    "updated_at"?: string | null;
    "created_at"?: string | null;
    "anonymous_users"?: number | null;
    "external_users"?: number | null;
    "internal_users"?: number | null;
    "period_end": string;
    "period_start": string;
    "period_key": string;
    "period_type": string;
    "project": string;
    "id"?: number;
      };
      Insert: {
    "wx_anonymous_users"?: number | null;
    "updated_at"?: string | null;
    "created_at"?: string | null;
    "anonymous_users"?: number | null;
    "external_users"?: number | null;
    "internal_users"?: number | null;
    "period_end": string;
    "period_start": string;
    "period_key": string;
    "period_type": string;
    "project": string;
    "id"?: number;
      };
      Update: {
    "wx_anonymous_users"?: number | null;
    "updated_at"?: string | null;
    "created_at"?: string | null;
    "anonymous_users"?: number | null;
    "external_users"?: number | null;
    "internal_users"?: number | null;
    "period_end"?: string;
    "period_start"?: string;
    "period_key"?: string;
    "period_type"?: string;
    "project"?: string;
    "id"?: number;
      };
      Relationships: [];
    };
    };
    Views: {};
    Functions: {};
    Enums: {

    };
    CompositeTypes: {};
  };
};
