create table if not exists public.todo (
	id bigint generated by default as identity primary key,
	title text not null,
	completed boolean not null default false,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now()
);
create index if not exists todo_updated_at_idx
	on public.todo (updated_at desc);